---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.4/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app hoarder
spec:
  releaseName: *app
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  maxHistory: 2
  install:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      hoarder:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/hoarder-app/hoarder
              tag: 0.23.0
            envFrom:
              - secretRef:
                  name: hoarder-secret
            env:
              BROWSER_WEB_URL: http://hoarder-chrome.media.svc.cluster.local:9222
              CRAWLER_DOWNLOAD_BANNER_IMAGE: true
              CRAWLER_ENABLE_ADBLOCKER: true
              CRAWLER_STORE_SCREENSHOT: true
              DATA_DIR: /data
              DISABLE_SIGNUPS: false
              MEILI_ADDR: http://hoarder-meilisearch.media.svc.cluster.local:7700
              NEXTAUTH_URL: https://hoarder.${SECRET_DOMAIN}
              DISABLE_NEW_RELEASE_CHECK: true
              COREPACK_INTEGRITY_KEYS: 0
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 1Gi

      chrome:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124
            command:
              - chromium-browser
            args:
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
            securityContext:
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

      meilisearch:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - hoarder
                      - key: app.kubernetes.io/component
                        operator: In
                        values:
                          - hoarder
                  topologyKey: kubernetes.io/hostname
        containers:
          app:
            image:
              repository: docker.io/getmeili/meilisearch
              tag: v1.13.3
            args:
              - /bin/meilisearch
              - --experimental-dumpless-upgrade
            envFrom:
              - secretRef:
                  name: hoarder-secret
            env:
              MEILI_NO_ANALYTICS: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 4Gi

    service:
      app:
        primary: true
        controller: hoarder
        ports:
          http:
            port: &port 3000
      chrome:
        controller: chrome
        ports:
          http:
            port: 9222
      meilisearch:
        controller: meilisearch
        ports:
          http:
            port: 7700

    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: hoarder
          gethomepage.dev/icon: hoarder.svg
          gethomepage.dev/description: Bookmark management
          gethomepage.dev/pod-selector: ""
          gethomepage.dev/widget.type: hoarder
          gethomepage.dev/widget.url: "http://hoarder.media.svc.cluster.local:3000"
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
        hosts:
          - host: &host hoarder.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: *app
        advancedMounts:
          hoarder:
            app:
              - path: /data
                subPath: hoarder
          meilisearch:
            app:
              - path: /meili_data
                subPath: meilisearch
      tmp:
        type: emptyDir
        globalMounts:
          - path: /.cache/
