---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app chizuru-dev
  namespace: flux-system
spec:
  targetNamespace: &namespace default
  path: ./kubernetes/apps/default/chizuru-dev/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substitute:
      APP: *app
