---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: &namespace external-secrets
spec:
  targetNamespace: *namespace
  path: ./kubernetes/apps/external-secrets/external-secrets/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app external-secrets
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-stores
  namespace: &namespace external-secrets
spec:
  targetNamespace: *namespace
  dependsOn:
    - name: external-secrets
  path: ./kubernetes/apps/external-secrets/external-secrets/stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: external-secrets-stores
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
