---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: recyclarr
  namespace: flux-system
spec:
  targetNamespace: &namespace media
  dependsOn:
    - name: radarr
    - name: sonarr
  path: ./kubernetes/apps/media/recyclarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app recyclarr
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: *app
      namespace: *namespace
  interval: 30m
  retryInterval: 1m
  timeout: 3m
