---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-unifi
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 30m
  dependsOn:
    - name: external-secrets
      namespace: external-secrets

  values:
    fullnameOverride: *app
    domainFilters: ["${SECRET_DOMAIN}"]
    extraArgs:
      - --ignore-ingress-tls-spec
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-unifi-secret
    policy: sync
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/kashalls/external-dns-unifi-webhook
          tag: v0.6.0
        envFrom:
          - secretRef:
              name: external-dns-unifi-secret
        env:
          - name: UNIFI_HOST
            value: https://192.168.0.1
          - name: UNIFI_API_KEY
            valueFrom:
              secretKeyRef:
                name: external-dns-unifi-secret
                key: UNIFI_API_KEY
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    resources:
      requests:
        cpu: 16m
        memory: 90Mi
      limits:
        memory: 128Mi
    serviceMonitor:
      enabled: true
    sources:
      - ingress
      - service
    triggerLoopOnEvent: true
    txtOwnerId: main
    txtPrefix: "k8s."

  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: *app
            patch: |
              - op: add
                path: /spec/template/spec/enableServiceLinks
                value: false
