---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: linkwarden-secret
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgres://{{ .LINKWARDEN_POSTGRES_USERNAME }}:{{ .LINKWARDEN_POSTGRES_PASSWORD }}@{{ .POSTGRES_HOSTNAME }}:5432/{{ .LINKWARDEN_DATABASE_NAME }}"
        NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"
        INIT_POSTGRES_DBNAME: "{{ .LINKWARDEN_DATABASE_NAME}}"
        INIT_POSTGRES_USER: "{{ .LINKWARDEN_POSTGRES_USERNAME }}"
        INIT_POSTGRES_PASS: "{{ .LINKWARDEN_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_HOST: "{{ .POSTGRES_HOSTNAME }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
  dataFrom:
    - extract:
        key: linkwarden
