# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:SjVEU/FNSRP7TEE5KkoY0n6dhhMsR8okRS8yZexhEblX7PkR2qxH/A==,iv:zjNIpNBRFDF3/TBHugVU4I8EHgtigEo8TYrkWtqWwtI=,tag:8xm33Num846tn8E6LIeCTw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fv4ar3tmcjqwfhhad59kjeza9tzvpjvdevzl7v34nz9yfk60vy6s970ur2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZjVkVC9TR2NXVW04bkJo
        K3IrQys0STAxWXNlUml4ZkErOGhySS9yY0drCnk5TytZLzRKaTZybFUvdDBWRkE2
        QWhtZHRSVTU5cGJDVzBzR29EQjBqMk0KLS0tIDB3TWlQa0k4ZThERSs2R0tkaUd1
        ZERGeTlzYTNvVG1UZi9NcDJpcmVCSFkK4vPh6eZ/4YI4jFRalk5eQ/yz5QaDlhCK
        NBEFGHHSPIMc2AnLvS1qeOe1wbtzgRBocpHJyCNp5Yrn3N0IrUeGnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T03:10:41Z"
  mac: ENC[AES256_GCM,data:CXKRg7+tTo6TWLblLXBICjvmdSSsNrDks0KYPFOO1kUOYnQV7DpwaM+DSBexaNR2oIOvU2tENCdPhGKB5p6r6qKJO6Ltqsawc2DQc88/h50xypcqznWjiOh7t+V9juOSBXirascTu6qSJTzPTHKgdM6bW7Tm896jBNcf+CNRJtA=,iv:hUgemwO2C9JNuyFBHefKsMkxXwFpYTBZUmgOOog6ZLw=,tag:lTUlECktOiRIwL+GQFY7kA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
