---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-5.0.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vrising
spec:
  releaseName: *app
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  upgrade:
    force: true
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: &uid 1000
        runAsGroup: &gid 100
        fsGroup: *gid
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      vrising:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: trueosiris/vrising
              tag: 3.0@sha256:a58cb84e3d69acf2d965ec752ee3a13ce5d10eea1808b536762fbd7048af71c2
            envFrom:
              - secretRef:
                  name: vrising-secret
            env:
              TZ: America/Chicago
              GAMEPORT: &game 9876
              QUERYPORT: &query 9877
              MAX_USERS: 10
              MAX_ADMIN: 4
              UID: *uid
              GID: *gid
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 1
                memory: 4Gi
              limits:
                memory: 8Gi
    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.10.115
        ports:
          game:
            port: *game
            protocol: UDP
          query:
            port: *query
            protocol: UDP
    persistence:
      data:
        enabled: true
        existingClaim: *app
        advancedMounts:
          vrising:
            app:
              - path: /mnt/vrising/persistentdata
      server:
        existingClaim: vrising-server-files
        advancedMounts:
          vrising:
            app:
              - path: /mnt/vrising/server
      game-settings:
        type: configMap
        name: vrising-game-settings
        advancedMounts:
          vrising:
            app:
              - path: /mnt/vrising/persistentdata/Settings/ServerGameSettings.json
                subPath: ServerGameSettings.json
                readOnly: true
