# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:rULA14oWGe2VNXQDcuDHB+HI+GLtEOmtbqlyIB3Ix5E=,iv:QQn7NRrmTKiGpEjmAhuxg7NjZV/riOi0vJJuEqo3DHs=,tag:CDY9TlbeRbr7x/7i9276SA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fv4ar3tmcjqwfhhad59kjeza9tzvpjvdevzl7v34nz9yfk60vy6s970ur2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WjNnelJSTE9RM3lmK2hp
        V0ZYblFHZHRQMTVhQXpKM0ZmZkIwZktlRFNRCktzQTFuMlRWVEpGNmtSN0RpWkdE
        ZktyOGJvdS9saTkzUkFJTXNtRlB4OWsKLS0tIFA5V1JkbHpHV1hQdG5sTGpFbXRq
        dG5PelRoaUhabVlSKzlrK2wxM1pNLzAKqoYhihcg0/QtaimM+KKeU4/1qvVBqXNx
        VsvuvSl4IpxbwcCau2EGVu9cWvStMjKIGoWSQNO75F15E7rpipBcfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T16:54:54Z"
  mac: ENC[AES256_GCM,data:+/o4vRRS8gTw7+Hb0c8F0FCB89G6SsT2vSAqeGfxGjVaLGg98xRcaG4Y3C8FVPlV88704G6cBkI0mxo7/iIiNYNWmwgU3wVhhgehDJtncPSvP2dQPKqGbLxt7O1YYPy6ULDcgsDy24X1i/E5nVPiAkGLx6/o9SpoL0Ma1jFioDM=,iv:7i0wHNrSCRWY6MZmDNs/oTRvj4yaD8XHIAstUUNHAKU=,tag:GaPMUrRXvcGDDlxPO+EuSQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
