# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Ey5qND+t7Mzvz5kB9xRJng26Vs4Jz2g+rK+YHMtGZPc=,iv:cahueKPmKLYe4sAtLFyeMPkcPwu0WS8ZzUaAZnJfjT0=,tag:V0r3+GgEzSBLjwoq+yGgAA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fv4ar3tmcjqwfhhad59kjeza9tzvpjvdevzl7v34nz9yfk60vy6s970ur2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VWhtYUdFcldoSVVzNDM2
        OVBTOC9VeFczOG9QRUhNMHVtclpWdTVCOEVvCnFHY0tRSkRGcVVHOUJxZW5EMEZI
        Y3dlYVBjNUQrYXUxZ2Q2Zmk3RGRMZW8KLS0tIFJFVGIzbFBPcXl6YThCaXBOQ1h0
        TWhsaklCTkF3QkdPR3lFYy9JOTJIRkUK0gAw9P1QLQ2E1gxP5ZoI/69HID4o5aaj
        AxdQ6m7DHZSyM4GsXyQPxF5jHIsY5YeWjZhruI8b20sJNaUNAL6djw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T03:10:41Z"
  mac: ENC[AES256_GCM,data:URvr6hSUXGpehr6VGWBf6FMETb58ARRaZKvfitFiZoiGF5hwc1y2osLPH8589igsQF6SXkDcjkVNXpJ+6xoIYFJ8TbjK5BzhrqjXoAssACF1szWdyNYvgE4DH0uHd1TxGYHmOv3XbEI2hLeTETV4gWfpv/JV9pBa3HlBNKAvVds=,iv:8yZMraYWgOYYDSsRQjBtrafLaZhQa/kzYqMw8apxf5M=,tag:mpZTFS+UMKx3IuEoNuOL+g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
