---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-secret.yaml
  - ./rbac.yaml
  - ./helm-release.yaml
configMapGenerator:
  - name: gatus-config-map
    files:
      - config.yaml=./config/gatus.yaml
generatorOptions:
  disableNameSuffixHash: true
