---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ganymede-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ganymede-secret
    template:
      engineVersion: v2
      data:
        DB_DATABASE_NAME: ganymede-prd
        DB_HOSTNAME: "{{ .POSTGRES_HOSTNAME }}"
        DB_USERNAME: "{{ .GANYMEDE_POSTGRES_USERNAME }}"
        DB_PASSWORD: "{{ .GANYMEDE_POSTGRES_PASSWORD }}"
        TWITCH_CLIENT_ID: "{{ .TWITCH_CLIENT_ID }}"
        TWITCH_CLIENT_SECRET: "{{ .TWITCH_CLIENT_SECRET }}"
        INIT_POSTGRES_DBNAME: ganymede-prd
        INIT_POSTGRES_USER: "{{ .GANYMEDE_POSTGRES_USERNAME }}"
        INIT_POSTGRES_PASS: "{{ .GANYMEDE_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_HOST: "{{ .POSTGRES_HOSTNAME }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: ganymede
