---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-4.2.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radarr
spec:
  releaseName: *app
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  maxHistory: 2
  install:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  upgrade:
    force: true
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      radarr:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 5.27.5.10184@sha256:af67ce80302e21f7228e2da671943c48b27a25faf27e19c4fcb7ad33c1c0e3c0
            envFrom:
              - secretRef:
                  name: radarr-secret
            env:
              TZ: America/Chicago
              RADARR__INSTANCE_NAME: Radarr
              RADARR__PORT: 7878
              RADARR__APPLICATION_URL: https://radarr.${SECRET_DOMAIN}
              RADARR__LOG_LEVEL: info
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 7878
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: Radarr
          gethomepage.dev/icon: radarr.svg
          gethomepage.dev/description: Movie management
          gethomepage.dev/widget.type: radarr
          gethomepage.dev/widget.url: "http://radarr.media.svc.cluster.local:7878"
          gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_RADARR_TOKEN}}` }}"
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
        hosts:
          - host: &host radarr.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: *app
      cache:
        existingClaim: radarr-cache
        globalMounts:
          - path: /config/MediaCover
      tmp:
        type: emptyDir
      media:
        type: nfs
        server: "192.168.10.42"
        path: /mnt/data/media
        globalMounts:
          - path: /media
