# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:fpn5QhbHL6YntFhswzAG71jX+lnnCBs4883l7vYqOXYj0iZ77N6bqP0X4yQAvw2AS92r03A=,iv:TVsy3+fQ0PETP2NmIYYunKpdz4cN7xfH+AhJIt7oZOc=,tag:FeFiS4v3PyhxTHIQEQLlAw==,type:str]
sops:
    age:
        - recipient: age1fv4ar3tmcjqwfhhad59kjeza9tzvpjvdevzl7v34nz9yfk60vy6s970ur2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMW1hZHUvc0FkdVUvL1BY
            UURIZ21KZWFRbE1iUCtMQ3E2di9MRXNmS25JCm5nZXFUQXU3N3NLWSsySUtycXM1
            OGlsRGRiT3FGQXFGNUluUmdPclV5S28KLS0tIDR1dEVOTjlZdlQ0TUVKc1ZEckhv
            b2R3UnZIVE5zLzUzU2M4eDlMbTM3U1EKOWAeOhv7qqxvl2pYyLLATZN6lzGbS754
            nu2N+8Icblx7nCih6jKbQtnUdioG/NZR2Rl/lsnrnJjRIxrUgewX3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T00:28:34Z"
    mac: ENC[AES256_GCM,data:RcahJzx6JVuqMx7Fs0KdCl48GR4fEpBRwdgfuJpmGi8I+lQjedi9Yb9r5iWAZAjG+S5cf30py/qxe+EPDx3Lx8UtICH9oXwi4inEcnLRo/LzyVTrpNdIQhtkKnLcJjZEG3MgDzWiFKD8NLtQ3V3vbdHJoy+T3Zy5qKYGLefE0vg=,iv:nvTu8olPxu7UmpkH48KEX/xZuGbx7WpG/13dj0hyABo=,tag:8M5GnymecouqAc3AHVQBew==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
