# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:R8EKwGa0nT+pJdqsxUDiMJ042p1vIXSkz3sn0RmXd1HDxnDyYk0sHw==,iv:oh+32s2ue27Jh0rEMGEJEVw7EY0Jtnhe6Tn17RZuybA=,tag:hsMzCSSdOPGmM0uNgm9L4w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fv4ar3tmcjqwfhhad59kjeza9tzvpjvdevzl7v34nz9yfk60vy6s970ur2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXS0JhcVl3WmtoeUtpdE5V
        akZFN2pkTFVwRkJZN3VSeDBQR01pMGdlNEh3CmJRTCtmYlNqMUl5d2psVzdSZW4z
        RzJ2cFRPYXBydU1ISmgweFlPYzdPalUKLS0tIEV1YWFFNFpkcUk3RTRGRTJua3RT
        SnRJMEZ1ZTZQbXdtNG1mRGxOS0RQUzAKV9DscaCFn6vVJdLpkUdF1sMX1IBVKg98
        QpkEPtTwxtL4Wz6l4bKmQhrF6urfiA4vbKNhSksgg9JpVv3D2Xearw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T03:10:41Z"
  mac: ENC[AES256_GCM,data:aEMFzVnDQHJDQ0Ea1jZEvC9bmQfgWLubb9plPXE18MDZvwN5WJM70cnexKedhXfWKKE+z+lQiXIa0nhrdHIkHJiLsYUffCg9KaCxnO+7Gu92njJkNANhEnxUyLlY2sY70MyWlJcT2cp+6upAWS9xZ5RG088VDIoVaoEcdBjJ2/g=,iv:bbpeKB1kg2o9w/cORrglD3XpbG5Wa5TAw6+n8P65pN0=,tag:ePnTY/xQMro5ElSnQcBO4g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
