# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:jad88jKrzodgEIo9gTSaPFxeDTWocpqTTU120JBSV/tDHOUprPnhJA==,iv:pstGpWRcyunqkyk1+0MvDy7uMmQiicWDQDFBW1Xv/Yw=,tag:SojC09/TA0LsJZSxQQ6W9Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fv4ar3tmcjqwfhhad59kjeza9tzvpjvdevzl7v34nz9yfk60vy6s970ur2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMW1hZHUvc0FkdVUvL1BY
        UURIZ21KZWFRbE1iUCtMQ3E2di9MRXNmS25JCm5nZXFUQXU3N3NLWSsySUtycXM1
        OGlsRGRiT3FGQXFGNUluUmdPclV5S28KLS0tIDR1dEVOTjlZdlQ0TUVKc1ZEckhv
        b2R3UnZIVE5zLzUzU2M4eDlMbTM3U1EKOWAeOhv7qqxvl2pYyLLATZN6lzGbS754
        nu2N+8Icblx7nCih6jKbQtnUdioG/NZR2Rl/lsnrnJjRIxrUgewX3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T16:54:54Z"
  mac: ENC[AES256_GCM,data:9dIOT3lzTQLsbpn3tPWMc1U/ekhF0e/jSpkch0xh6rxZe1DIKIb2vAKRh6nRnNshtZHP+MmFfcccniZK8sJSC9l2mA2E6t6LdFRyaUIuvc2aEsXA0V3XS8FEK2T3Xxm9DuuR7HQ7+Az3VBlgFcKWgtq7yOYMDbHWCkfdaG4A5dg=,iv:eCX9GVP+gEXR2CquXkei8Lm4Z5Z1hJicvJOnEyA2F3E=,tag:gURBkrp3QVDwVuQjM+ePPQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
