---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg
  namespace: &namespace database
spec:
  targetNamespace: *namespace
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: external-secrets-stores
      namespace: external-secrets
  path: ./kubernetes/apps/database/cloudnative-pg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: *app
      namespace: *namespace
  interval: 30m
  retryInterval: 1m
  timeout: 3m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pg-cluster
  namespace: &namespace database
spec:
  targetNamespace: *namespace
  dependsOn:
    - name: cloudnative-pg
  path: ./kubernetes/apps/database/cloudnative-pg/config
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  retryInterval: 1m
  timeout: 3m
