---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.5.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app foundryvtt
spec:
  releaseName: *app
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  maxHistory: 2
  install:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      foundryvtt:
        containers:
          app:
            image:
              repository: felddy/foundryvtt
              tag: 12.331.0
            envFrom:
              - secretRef:
                  name: foundry-secret
            env:
              TIMEZONE: America/Chicago
              CONTAINER_CACHE: /data/container_cache
              CONTAINER_PATCHES: /data/container_patches
              CONTAINER_URL_FETCH_RETRY: '50'
              CONTAINER_VERBOSE: 'true'
              FOUNDRY_HOSTNAME: foundry.${SECRET_DOMAIN}
              FOUNDRY_LOCAL_HOSTNAME: foundry.${SECRET_DOMAIN}
              FOUNDRY_MINIFY_STATIC_FILES: 'true'
              FOUNDRY_PROTOCOL: '4'
              FOUNDRY_PROXY_PORT: '443'
              FOUNDRY_PROXY_SSL: 'true'
              FOUNDRY_COMPRESS_WEBSOCKET: 'true'
              FOUNDRY_TELEMETRY: 'false'
            resources:
              requests:
                memory: 256Mi
              limits:
                memory: 1024Mi
          filebrowser:
            env:
              TZ: "${TIMEZONE}"
            image:
              repository: filebrowser/filebrowser
              tag: v2.31.2-s6
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 30000
      filebrowser:
        controller: *app
        primary: false
        ports:
          filebrowser:
            port: 80
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Games
          gethomepage.dev/name: Foundry
          gethomepage.dev/icon: foundry-vtt.png
          gethomepage.dev/description: Virtual table top
        hosts:
          - host: &host foundry.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: &host-filebrowser foundry-files.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: filebrowser
        tls:
          - hosts:
              - *host
              - *host-filebrowser
    persistence:
      data:
        enabled: true
        existingClaim: *app
        advancedMounts:
          foundryvtt:
            app:
              - path: /data
            filebrowser:
              - path: /db
                subPath: filebrowser
              - path: /srv/data
