---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unpoller
spec:
  releaseName: *app
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      unpoller:
        containers:
          app:
            image:
              repository: ghcr.io/unpoller/unpoller
              tag: v2.13.1
            env:
              TZ: "America/Chicago"
              UP_UNIFI_DEFAULT_ROLE: home-ops
              UP_UNIFI_DEFAULT_URL: https://192.168.0.1
              UP_UNIFI_DEFAULT_VERIFY_SSL: false
              UP_INFLUXDB_DISABLE: true
            envFrom:
              - secretRef:
                  name: unpoller-secret
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 9130
    serviceMonitor:
      app:
        serviceName: unifi-poller
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 2m # Unifi API only polls at 2m intervals
            scrapeTimeout: 30s
