---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app foundryvtt
  namespace: flux-system
spec:
  targetNamespace: &namespace games
  dependsOn:
    - name: external-secret-store
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
  components:
    - ../../../../components/volsync
  path: ./kubernetes/apps/games/foundryvtt/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: *app
      namespace: *namespace
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
      substitute:
        APP: *app
        VOLSYNC_CAPACITY: 24Gi
        VOLSYNC_CACHE_CAPACITY: 12Gi
