apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:IAOPQr1kagZj,iv:iOjNTIdDJK4yzJQsFU6fag1+qKMt9sLRCVPbtyWaQq4=,tag:c6YVe/sSxupLxIoEzkCGjA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:MU5VbQIX/sRG83MFy4hTVQ==,iv:KGi2c8s4PnLInW4x7o38Ku4343MALSrIgLM9CXSvJBs=,tag:QJdLaAwZhIVBIHU4y7PeLA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:LvrIEKuY1cMh0BSEEXI2H74xyShIeNXTeY2w971RVD8k1K+T,iv:S8Y5IOH9imgrgMJddNlCxzLx/813Hwzfx81rOTJ2yiQ=,tag:z78+LCjTu3h+2/yOlGlUmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fv4ar3tmcjqwfhhad59kjeza9tzvpjvdevzl7v34nz9yfk60vy6s970ur2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QnRhTVZPSUFSSXlka0dR
            Z3pZOFZmUnBDa1JHTG5ZN2krZzZuRWwzTm00CnBSSEZMU1lSV0JqVzgvVXZwQ2xP
            R3ZDaEh6TWZYUzZyVmVxOFNzdFlRYjgKLS0tIHlxeVk3QUVBM2JiMDF1UVBocGdT
            U3hXWFdES0E0V01LdWNDSExHb3gwQUEK2aiStLLYF1sSwnI0j86x/sdymR8+BG2K
            UWax4orWgo59mwkBcDnJO5/pSVKSmXdMPAVnCtIQJkPeWGiORUqlgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T05:31:14Z"
    mac: ENC[AES256_GCM,data:gDJtaCpgtPwZTbo7ScQmcrSnf4gJi5dwH5d6cLNsUV6bph52ZhBDgXF94IJVS8lbd7qWm/1MQ15uLanmwcbLn23Krzk6BrQjDe3qDs7EOggqCWPIKnVflr580XtSGywtK7W2rFx6rezaJ0EW23jhWsuv0XLDo9KypoJXuQomvPM=,iv:7ku9rK42GVDh2f/1+vvdXx6QQmJOkH2xJj8iXwHCAJA=,tag:gPe3IqJCLbQz1WY3QaWAPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
