---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.4/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app chizuru-prd
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  releaseName: *app
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      chizuru-prd:
        containers:
          app:
            image:
              repository: ghcr.io/aylamar/chizuru-bot
              tag: latest@sha256:b648d6059054eef4c36bc1602bdfb38d4dbae4498e3bedbca27409a19c0659b2
            env:
              TZ: America/Chicago
            envFrom:
              - secretRef:
                  name: chizuru-prd-secret
            resources:
              requests:
                cpu: 15m
                memory: 64Mi
              limits:
                memory: 256Mi
