---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app promtail
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      version: 6.17.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  maxHistory: 3
  install:
    crds: Skip
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: promtail
    config:
      clients:
        - url: http://loki-headless.observability.svc.cluster.local:3100/loki/api/v1/push
    serviceMonitor:
      enabled: true
