---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    # - Media:
    #     - YouTube:
    #         - icon: youtube.svg
    #           href: 'https://youtube.com/feed/subscriptions'
    #     - Spotify:
    #         - icon: spotify.svg
    #           href: 'http://open.spotify.com'
    # - Git:
    #     - kubesearch:
    #         - icon: kubernetes-dashboard.svg
    #           href: 'https://kubesearch.dev/'
    #     - home-ops:
    #         - icon: github.svg
    #           href: 'https://github.com/aylamar/home-ops'
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
    ingress: true
  services.yaml: |
    # - Calendar:
    #     - Agenda:
    #         widget:
    #           type: calendar
    #           view: agenda # optional - possible values monthly, agenda
    #           maxEvents: 15 # optional - defaults to 10
    #           integrations: # optional
    #             - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
    #               service_group: Downloads # group name where widget exists
    #               service_name: Sonarr # service name for that widget
    #             - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
    #               service_group: Downloads # group name where widget exists
    #               service_name: Radarr # service name for that widget
    #             - type: readarr # active widget type that is currently enabled on homepage - possible values: radarr, sonar>
    #               service_group: Downloads # group name where widget exists
    #               service_name: Readarr # service name for that widget
    - Infrastructure:
        - TrueNAS:
            href: http://192.168.10.42
            icon: truenas.svg
            description: Bulk storage via TrueNAS
        - Unraid:
            href: http://192.168.10.43
            icon: unraid.svg
            description: Bulk storage via Unraid
    - Home:
        - Unifi:
            href: https://unifi.ui.com
            icon: unifi.svg
            description: Unifi Dashboard
            widget:
              type: unifi
              url: https://192.168.0.1:443
              username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
              password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
  settings.yaml: |
    title: Dashboard
    useEqualHeights: true
    theme: dark
    color: slate
    headerStyle: clean
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Media:
        style: row
        columns: 3
        icon: mdi-play-circle
      Games:
        style: row
        columns: 1
        icon: mdi-minecraft
      Observability:
        style: row
        columns: 2
        icon: mdi-chart-line
      Home:
        style: row
        columns: 2
        icon: mdi-home-analytics
      Downloads:
        style: row
        columns: 4
        icon: mdi-download-circle
      Infrastructure:
        style: row
        columns: 4
        icon: mdi-server
  widgets.yaml: |
    - search:
        provider: [custom]
        url: https://kagi.com/search?q=
        focus: false
        showSearchSuggestions: false
        target: _blank
    - kubernetes:
        cluster:
          show: false
        nodes:
          cpu: true
          memory: true
          show: true
          showLabel: true
