---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        ## Default
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .HOME_ASSISTANT_TOKEN }}"
        ## Downloads
        HOMEPAGE_VAR_BAZARR_TOKEN: "{{ .BAZARR_API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_QBITTORRENT_USERNAME: "{{ .QBITTORRENT_USERNAME }}"
        HOMEPAGE_VAR_QBITTORRENT_PASSWORD: "{{ .QBITTORRENT_PASSWORD }}"
        HOMEPAGE_VAR_LIDARR_TOKEN: "{{ .LIDARR_API_KEY }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_READARR_TOKEN: "{{ .READARR_API_KEY }}"
        HOMEPAGE_VAR_SABNZBD_TOKEN: "{{ .SABNZBD_API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
        ## Media
        HOMEPAGE_VAR_IMMICH_TOKEN: "{{ .IMMICH_API_KEY }}"
        HOMEPAGE_VAR_PLEX_TOKEN: "{{ .PLEX_SERVER_TOKEN }}"
        # HOMEPAGE_VAR_TAUTULLI_TOKEN: "{{ .TAUTULLI_API_KEY }}"
        ## Monitoring
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .UNIFI_USERNAME }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .UNIFI_PASSWORD }}"
        # HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_ADMIN_USER }}"
        # HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_ADMIN_PASS }}"
  dataFrom:
  - extract:
      key: bazarr
  # - extract:
  #     key: grafana
  - extract:
      key: home-assistant
  - extract:
      key: immich
  - extract:
      key: lidarr
  - extract:
      key: plex
  - extract:
      key: prowlarr
  - extract:
      key: qbittorrent
  - extract:
      key: radarr
  - extract:
      key: readarr
  - extract:
      key: sabnzbd
  - extract:
      key: sonarr
  # - extract:
  #     key: tautulli
  - extract:
      key: unifi
