---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.4/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex-meta-manager
spec:
  releaseName: plex-meta-manager
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: plex
      namespace: media
  maxHistory: 2
  install:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      plex-meta-manager:
        type: cronjob
        annotations:
          reloader.stakater.com/auto: "true"
        cronjob:
          schedule: 0 6 * * *
        containers:
          app:
            image:
              repository: docker.io/meisnate12/plex-meta-manager
              tag: v1.21.0
            command:
              - /scripts/run.sh
            env:
              TZ: America/New_York
              PUID: 568
              PGID: 568
            envFrom:
              - secretRef:
                  name: plex-meta-manager-secret
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 500Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
      # scripts:
      #   type: configMap
      #   name: plex-meta-manager-configmap
      #   defaultMode: 0775
      #   globalMounts:
      #     - path: /scripts/run.sh
      #       subPath: run.sh
    service:
      app:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: pmm-config-pvc
      config-file:
        type: configMap
        name: plex-meta-manager-configmap
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
