---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app plex
  namespace: flux-system
spec:
  targetNamespace: &namespace media
  dependsOn:
    - name: external-secrets-stores
  path: ./kubernetes/apps/media/plex/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: *app
      namespace: *namespace
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
      substitute:
        APP: *app
        GATUS_PATH: /web/index.html
        VOLSYNC_CAPACITY: 32Gi
        VOLSYNC_CACHE_CAPACITY: 24Gi
