# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# A starter config to use with Recyclarr. Most values are set to "reasonable defaults". Update the
# values below as needed for your instance. You will be required to update the API Key and URL for
# each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple. Note that there's no "one
# size fits all" configuration. Please refer to the guide to understand how to build the appropriate
# configuration based on your hardware setup and capabilities.
#
# For any lines that mention uncommenting YAML, you simply need to remove the leading hash (`#`).
# The YAML comments will already be at the appropriate indentation.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://recyclarr.dev/wiki/reference/config-reference

# Configuration specific to Sonarr
sonarr:
  series:
    # Set the URL/API Key to your actual instance
    base_url: http://sonarr.media.svc.cluster.local:8989
    api_key: !env_var SONARR__API_KEY

    # Set to 'true' to automatically remove custom formats from Radarr when they are removed from the guide or your configuration. This will NEVER delete custom formats you manually created!
    delete_old_custom_formats: true

    # Instruct recyclarr to replace custom formats (old behavior)
    replace_existing_custom_formats: true

    # Quality definitions from the guide to sync to Sonarr. Choices: series, anime
    quality_definition:
      type: anime

    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-custom-formats-web-1080p

    custom_formats:
      - trash_ids:
          # Optional
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          # - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p

# Configuration specific to Radarr.
radarr:
  movies:
    # Set the URL/API Key to your actual instance
    base_url: http://radarr.media.svc.cluster.local:7878
    api_key: !env_var RADARR__API_KEY

    # Which quality definition in the guide to sync to Radarr. Only choice right now is 'movie'
    quality_definition:
      type: movie

    # Set to 'true' to automatically remove custom formats from Radarr when they are removed from the guide or your configuration. This will NEVER delete custom formats you manually created!
    delete_old_custom_formats: true

    # Instruct recyclarr to replace custom formats (old behavior)
    replace_existing_custom_formats: true

    include:
      # Comment out any of the following includes to disable them
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime
      - template: radarr-quality-profile-remux-web-1080p
      - template: radarr-custom-formats-remux-web-1080p

    # Custom Formats: https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/
    # A list of custom formats to sync to Radarr.
    # Use `recyclarr list custom-formats radarr` for values you can put here.
    custom_formats:
      # Misc Anime
      - trash_ids:
          - a5d148168c4506b55cf53984107c396e # 10bit
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 10

      # Dual Audio
      - trash_ids:
          # https://trash-guides.info/Radarr/radarr-setup-quality-profiles-anime/#dual-audio-scoring
          - 418f50b10f1907201b6cfdf881f467b7  # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 2000

      # Audio
      # - trash_ids:
      #     # Uncomment the next section to enable Advanced Audio Formats
      #     # - 496f355514737f7d83bf7aa4d24f8169 # TrueHD Atmos
      #     # - 2f22d89048b01681dde8afe203bf2e95 # DTS X
      #     # - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
      #     # - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
      #     # - 3cafb66171b47f226146a0770576870f # TrueHD
      #     # - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
      #     # - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
      #     # - e7c2fcae07cbada050a0af3357491d7b # PCM
      #     # - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
      #     # - 185f1dd7264c4562b9022d963ac37424 # DD+
      #     # - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
      #     # - 1c1a4c5e823891c75bc50380a6866f73 # DTS
      #     # - 240770601cc226190c367ef59aba7463 # AAC
      #     # - c2998bd0d90ed5621d8df281e839436e # DD
      #   assign_scores_to:
      #     - name: Remux + WEB 1080p

      # Movie Versions
      - trash_ids:
          - 0f12c086e289cf966fa5948eac571f44 # Hybrid
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to:
          - name: Remux + WEB 1080p
